//! Real vanilla item ids. MincScript items are **in-game items**, not heap objects.
//!
//! `Items.GOLD_INGOT` must exist in the snapshot. Traits (`named`, `lore`,
//! `enchant`, `lock`, `glow`, `tag`) are compile-time patches on that stack.

/// Un-namespaced vanilla item ids (1.21), sorted for binary search.
const VANILLA: &[&str] = &[
    "acacia_boat",
    "air",
    "amethyst_shard",
    "apple",
    "arrow",
    "baked_potato",
    "bamboo",
    "beef",
    "beetroot",
    "birch_boat",
    "blaze_powder",
    "blaze_rod",
    "bone",
    "bone_meal",
    "book",
    "bow",
    "bowl",
    "bread",
    "brick",
    "bucket",
    "carrot",
    "chainmail_boots",
    "chainmail_chestplate",
    "chainmail_helmet",
    "chainmail_leggings",
    "charcoal",
    "chest",
    "chicken",
    "chorus_fruit",
    "clay_ball",
    "clock",
    "coal",
    "cobblestone",
    "cod",
    "compass",
    "cooked_beef",
    "cooked_chicken",
    "cooked_cod",
    "cooked_porkchop",
    "cookie",
    "copper_ingot",
    "crossbow",
    "dark_oak_boat",
    "diamond",
    "diamond_axe",
    "diamond_boots",
    "diamond_chestplate",
    "diamond_helmet",
    "diamond_hoe",
    "diamond_horse_armor",
    "diamond_leggings",
    "diamond_pickaxe",
    "diamond_shovel",
    "diamond_sword",
    "dirt",
    "egg",
    "elytra",
    "emerald",
    "end_crystal",
    "ender_pearl",
    "experience_bottle",
    "feather",
    "fermented_spider_eye",
    "filled_map",
    "fire_charge",
    "firework_rocket",
    "fishing_rod",
    "flint",
    "flint_and_steel",
    "ghast_tear",
    "glass_bottle",
    "glistering_melon_slice",
    "glowstone_dust",
    "gold_block",
    "gold_ingot",
    "gold_nugget",
    "golden_apple",
    "golden_axe",
    "golden_boots",
    "golden_carrot",
    "golden_chestplate",
    "golden_helmet",
    "golden_hoe",
    "golden_leggings",
    "golden_pickaxe",
    "golden_shovel",
    "golden_sword",
    "gunpowder",
    "heart_of_the_sea",
    "honey_bottle",
    "ink_sac",
    "iron_axe",
    "iron_boots",
    "iron_chestplate",
    "iron_door",
    "iron_helmet",
    "iron_hoe",
    "iron_ingot",
    "iron_leggings",
    "iron_nugget",
    "iron_pickaxe",
    "iron_shovel",
    "iron_sword",
    "jungle_boat",
    "kelp",
    "lapis_lazuli",
    "lava_bucket",
    "lead",
    "leather",
    "leather_boots",
    "leather_chestplate",
    "leather_helmet",
    "leather_leggings",
    "lily_pad",
    "map",
    "melon_slice",
    "milk_bucket",
    "name_tag",
    "nether_brick",
    "nether_star",
    "netherite_axe",
    "netherite_boots",
    "netherite_chestplate",
    "netherite_helmet",
    "netherite_hoe",
    "netherite_ingot",
    "netherite_leggings",
    "netherite_pickaxe",
    "netherite_scrap",
    "netherite_shovel",
    "netherite_sword",
    "oak_boat",
    "oak_log",
    "oak_planks",
    "oak_sign",
    "paper",
    "phantom_membrane",
    "poisonous_potato",
    "popped_chorus_fruit",
    "porkchop",
    "potato",
    "potion",
    "prismarine_crystals",
    "prismarine_shard",
    "pufferfish",
    "pumpkin_pie",
    "quartz",
    "rabbit",
    "rabbit_foot",
    "rabbit_hide",
    "raw_copper",
    "raw_gold",
    "raw_iron",
    "redstone",
    "rotten_flesh",
    "saddle",
    "salmon",
    "scute",
    "shears",
    "shield",
    "shulker_shell",
    "slime_ball",
    "snowball",
    "spider_eye",
    "spruce_boat",
    "stick",
    "stone",
    "stone_axe",
    "stone_hoe",
    "stone_pickaxe",
    "stone_shovel",
    "stone_sword",
    "string",
    "sugar",
    "sweet_berries",
    "tnt",
    "torch",
    "totem_of_undying",
    "trident",
    "turtle_helmet",
    "water_bucket",
    "wheat",
    "wheat_seeds",
    "wooden_axe",
    "wooden_hoe",
    "wooden_pickaxe",
    "wooden_shovel",
    "wooden_sword",
    "writable_book",
    "written_book",
];

/// True if `id` is a real Minecraft item (with or without `minecraft:`).
pub fn is_real_item(id: &str) -> bool {
    let id = normalize(id);
    VANILLA.binary_search(&id.as_str()).is_ok()
}

pub fn normalize(id: &str) -> String {
    id.trim()
        .trim_start_matches("minecraft:")
        .replace('-', "_")
        .to_lowercase()
}

/// Field name `GOLD_INGOT` → `gold_ingot`.
pub fn from_const_name(name: &str) -> String {
    normalize(name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_is_sorted_and_contains_metro_items() {
        let mut sorted = VANILLA.to_vec();
        sorted.sort();
        sorted.dedup();
        assert_eq!(sorted, VANILLA, "VANILLA must be unique and sorted");
        assert!(is_real_item("gold_ingot"));
        assert!(is_real_item("minecraft:iron_ingot"));
        assert!(is_real_item("GOLD_INGOT"));
        assert!(!is_real_item("not_an_item_xyz"));
    }
}
